# windows_container:
#   image: cirrusci/windowsservercore:2019
  
assemble_task:
  env:
    API_LEVEL: 28
    TARGET: default
    ARCH: x86_64
  container:
    image: reactivecircus/android-emulator-28:latest
    kvm: true
    cpu: 8
    memory: 24G  
  # create_device_script:
  #   echo no | avdmanager create avd --force --name "api-${API_LEVEL}" --abi "${TARGET}/${ARCH}" --package "system-images;android-${API_LEVEL};${TARGET};${ARCH}"
  # start_emulator_background_script:
  #   $ANDROID_HOME/emulator/emulator -avd "api-${API_LEVEL}" -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
  # wait_for_emulator_script:
  assemble_script:
    $ANDROID_HOME/emulator/emulator -accel-check